name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SKIP_ENV_VALIDATION: true
  COREPACK_ENABLE_STRICT: 0

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: TypeScript
        run: pnpm typecheck
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: ESlint
        run: pnpm lint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Prettier
        run: pnpm format:check
